/* Generated by tools/make_numbers.py from data/facts.tsv and data/equipment.tsv. Do not edit. */
window.FOURMS_NUMBERS = {
 "founded": 2008,
 "audience": 20,
 "mocap-hz": 500,
 "audio-channels": 24,
 "speakers": 24,
 "users-internal": 30,
 "users-external": 20,
 "users-international-pct": 50,
 "user-countries": 13,
 "mooc-learners": 10000,
 "equivital": 70,
 "projects-active": 9,
 "projects-completed": 20,
 "movesense": 20,
 "eye-trackers": 7,
 "years": 18,
 "musiclab": 14,
 "standstill-recordings": 1594,
 "standstill-championship": 722,
 "standstill-collections": 7,
 "standstill-first-year": 2011,
 "standstill-last-year": 2025
};
window.FOURMS_EQUIPMENT = {
 "lab": {
  "Motion capture": [
   "Qualisys optical motion capture, 13 Oqus cameras",
   "Optitrack optical motion capture, 2 × 8 cameras",
   "Xsens MVN full-body mobile motion capture",
   "Polhemus Patriot magnetic 6-DOF tracking"
  ],
  "Biosignals": [
   "MEGA biosignal sensors, 4 EMG and 2 IMU",
   "Delsys biosignal sensors, 8 EMG and 4 ECG",
   "Sweetzpot respiration sensors, 10"
  ],
  "Sound": [
   "24 Genelec 8020B loudspeakers on a truss",
   "Wavefield synthesis array, 24 channels",
   "2 hemispherical 6-channel loudspeakers",
   "SSL AD/DA converters and RME MADIface XT"
  ],
  "Instruments": [
   "TouchKeys, Roli Seaboard Grand, Soundplane, LinnStrument, ContinuuMini"
  ]
 },
 "portable": {
  "Motion capture": [
   "Optitrack Flex 13 optical motion capture",
   "Nansense motion capture suits with gloves"
  ],
  "Eyes": [
   "Pupil Labs Pupil Core, 4",
   "Pupil Labs Neon, 3"
  ],
  "Wearables": [
   "AX3 accelerometers",
   "Delsys EMG: 8 Trigno, 2 FSR, 4 ECG",
   "Equivital: motion, ECG, respiration and skin temperature, 70",
   "Movesense: IMU and ECG, 20"
  ],
  "Video": [
   "GoPros, camcorders, thermal cameras",
   "White, coloured and infrared lighting; video mixers and recorders"
  ],
  "Sound": [
   "Soundcards, mixers, microphones and recorders; electronic pianos and drums"
  ]
 }
};
