#!/usr/bin/env python3
"""Write js/numbers.js, the numbers shown on the slides.

The equipment list comes from data/equipment.tsv. The quoted figures come from data/facts.tsv, where every row names its public source. Two numbers
are counted here: the years since the lab got its name, and the MusicLab editions, counted in the
events chapter of RITMO's final report when RITMO_REPORT points to its folder, and the Oslo
Standstill Database, counted in the harmonised measures table of the Still Standing project when
STANDSTILL_MEASURES points to it (otherwise the counts from the last run are kept).

    RITMO_REPORT=<final report folder> STANDSTILL_MEASURES=<deposit/harmonised/measures.csv> \
        .venv/bin/python tools/make_numbers.py
"""
import csv
import datetime
import json
import os
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
OUT = HERE / "js/numbers.js"


def musiclab_editions(report):
    tex = (Path(report) / "content/08-events.tex").read_text(encoding="utf-8")
    block = tex.split(r"\eventcategory{MusicLab Editions}", 1)[1].split(r"\eventcategory", 1)[0]
    return len(re.findall(r"^\\eventitem\{", block, re.M))


def standstill(measures):
    """Counts from the harmonised layer of the Oslo Standstill Database (Still Standing project)."""
    with open(measures, encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    years = [r["date"][:4] for r in rows if r["date"]]
    return {
        "standstill-recordings": len(rows),
        "standstill-championship": sum(r["collection"] == "Championships" for r in rows),
        "standstill-collections": len({r["collection"] for r in rows}),
        "standstill-first-year": int(min(years)),
        "standstill-last-year": int(max(years)),
    }


def main():
    with open(HERE / "data/facts.tsv", encoding="utf-8") as f:
        n = {r["key"]: int(r["value"]) for r in csv.DictReader(f, delimiter="\t")}
    n["years"] = datetime.date.today().year - n["founded"]
    old = {}
    if OUT.exists():
        old = json.loads(OUT.read_text().split("window.FOURMS_NUMBERS = ", 1)[1].split(";\n", 1)[0])
    report = os.environ.get("RITMO_REPORT")
    n["musiclab"] = musiclab_editions(report) if report else old.get("musiclab")
    measures = os.environ.get("STANDSTILL_MEASURES")
    keys = ("standstill-recordings", "standstill-championship", "standstill-collections",
            "standstill-first-year", "standstill-last-year")
    n.update(standstill(measures) if measures else {k: old.get(k) for k in keys})
    with open(HERE / "data/equipment.tsv", encoding="utf-8") as f:
        eq = {}
        for r in csv.DictReader(f, delimiter="\t"):
            eq.setdefault(r["where"], {}).setdefault(r["group"], []).append(r["item"])
    OUT.write_text("/* Generated by tools/make_numbers.py from data/facts.tsv and data/equipment.tsv."
                   " Do not edit. */\n"
                   "window.FOURMS_NUMBERS = " + json.dumps(n, indent=1, ensure_ascii=False) + ";\n"
                   "window.FOURMS_EQUIPMENT = " + json.dumps(eq, indent=1, ensure_ascii=False) + ";\n")
    print(n)


if __name__ == "__main__":
    main()
